[package]
name = "libogc-sys"
version = "0.1.0"
authors = ["Edu Renesto <edure95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libogc_sys"
crate-type = ["rlib"]

[dependencies]
